:Author: Elidiane
:Email: {ellydiani@gmail.com}
:Date: 04/11/2022
:Revision: version#
:License: Public Domain

= Project: Bingui Fuzzy Rule
FRB-BlinGui: Um Modelo Baseado em Regras Fuzzy para Previsão de Riscos de Colisão com Obstáculos em Apoio a Pessoas com Deficiência Visual
É possível observar na literatura que diversas abordagens são desenvolvidas para a navegação segura e orientação de pessoas com deficiência visual, visando evitar colisões com obstáculos. Essas abordagens frequentemente utilizam sensores ultrassônicos ou infravermelhos, aplicativos móveis com o auxílio de câmeras para visão computacional ou dispositivos vestíveis. No entanto, as incertezas e imprecisões decorrentes da dinâmica do ambiente muitas vezes são negligenciadas, tornando a navegação e orientação para pessoas com deficiência visual inseguras e sujeitas a vários tipos de colisões com diversos tipos de obstáculos. Diante dessa situação, surge a necessidade de desenvolver abordagens que considerem o grau de risco de colisão apresentado por cada obstáculo, considerando a dinâmica no deslocamento entre o indivíduo e o obstáculo, bem como a sua localização em pontos altos ou baixos de difícil percepção. Nesse contexto, a Teoria de Conjuntos Fuzzy (TCF) apresenta-se como um ferramental essencial para lidar com a imprecisão e as incertezas existentes no ambiente, uma vez que o uso de sistemas baseados na TCF possuem a vantagem da interpretação intuitiva do comportamento do usuário. Sendo assim, este projjeto apresenta um modelo inovador para detecção de obstáculos e previsão de riscos de colisões em cenários dinâmicos, denominado FRB-BlinGui (Modelo de navegação e orientação cega baseado em regras fuzzy). O modelo proposto foi testado em um dispositivo vestível para detectar obstáculos e prevenir colisões em tempo real, oferecendo alertas graduais sobre os riscos. Os resultados mostram sua eficácia ao fornecer alertas, prometendo melhorar a segurança e mobilidade de pessoas com deficiência visual.


== Step: Installation

1. Abrir os arquivos na IDE do arduíno
2. fazer upload do cógigo do dispositivo vestível blingui

== Step 2: Dispositivo Vestível Blingui
A imagem do dispositivo e do circuito é apresentado na figura blingui.png
== Step 3:carega o código no dispositivo blingui 
upload do código no dispositivo vestível
